"""
Django settings for restaurant_project project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$f%u-n86t1avig@3om(jcaq!%6c^tmfg40m3xy7aq=hp6@4drd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

LOGIN_URL = 'login'  # This is the crucial setting you were missing
LOGIN_REDIRECT_URL = 'index'  # The page you want to redirect to after login
LOGOUT_REDIRECT_URL = 'login'  # The page you want to redirect to after logout
# Application definition

INSTALLED_APPS = [
    'restaurant',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'restaurant_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'restaurant_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False  # Important: Must be False when using TLS
EMAIL_TIMEOUT = 10  # Timeout in seconds for SMTP operations
EMAIL_HOST_USER = 'johnchuli982@gmail.com'  # Your Gmail address
EMAIL_HOST_PASSWORD = 'qqenumdlwkvrkxii'  # App-specific password

# Email Display Settings
SITE_NAME = "Baraka Rescue Restaurant"  # Your restaurant name
DEFAULT_FROM_EMAIL = 'Baraka Rescue Restaurant <johnchuli982@gmail.com>'  # Format: "Name <email>"
REPLY_TO_EMAIL = 'info@barakarescuerestaurant.com'  # For customer replies
CONTACT_PHONE = "+254 114 601620"  # Your restaurant phone number
SERVER_EMAIL = 'alerts@barakarescuerestaurant.com'  # For error notifications

# Email Security Settings
EMAIL_SSL_CERTFILE = None  # Path to certificate if needed
EMAIL_SSL_KEYFILE = None  # Path to private key if needed
EMAIL_SUBJECT_PREFIX = '[BarakaRescueRestaurant] '  # Prefix for all email subjects

# Email Headers
EMAIL_EXTRA_HEADERS = {
    'X-Entity-Ref-ID': 'BARAKARESCUE-RESTAURANT',  # For tracking in mail servers
    'X-Mailer': 'Django Restaurant System'
}