# Generated by Django 4.2.7 on 2023-11-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=500)),
                ('btn', models.CharField(max_length=20)),
                ('image', models.ImageField(default='homepage.jpg', upload_to='homepage')),
            ],
        ),
    ]
