# Generated by Django 4.2.7 on 2023-11-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=50)),
                ('heading', models.CharField(max_length=150)),
                ('description', models.TextField(default='description of the restaurant', max_length=4500)),
            ],
        ),
    ]
