# Generated by Django 4.2.7 on 2023-11-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_rename_date_customer_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(default='stories.jpg', upload_to='stories')),
                ('image2', models.ImageField(default='stories.jpg', upload_to='stories')),
                ('image3', models.ImageField(default='stories.jpg', upload_to='stories')),
                ('image4', models.ImageField(default='stories.jpg', upload_to='stories')),
                ('image5', models.ImageField(default='stories.jpg', upload_to='stories')),
                ('image6', models.ImageField(default='stories.jpg', upload_to='stories')),
                ('text1', models.CharField(default='text1', max_length=500)),
                ('text2', models.CharField(default='text2', max_length=500)),
                ('text3', models.CharField(default='text3', max_length=500)),
                ('text4', models.CharField(default='text4', max_length=500)),
                ('text5', models.CharField(default='text5', max_length=500)),
                ('text6', models.CharField(default='text6', max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='image',
            new_name='background_image1',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='about',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='category',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='price',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='image1',
            field=models.ImageField(default='aboutpage.jpg', upload_to='aboutpage'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='image2',
            field=models.ImageField(default='aboutpage.jpg', upload_to='aboutpage'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='image3',
            field=models.ImageField(default='aboutpage.jpg', upload_to='aboutpage'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='special',
            field=models.CharField(default='specialmenu', max_length=500),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='text1',
            field=models.CharField(default='text1', max_length=500),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='text2',
            field=models.CharField(default='text2', max_length=500),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='text3',
            field=models.CharField(default='text3', max_length=500),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='welcome',
            field=models.CharField(default='welcome', max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image1',
            field=models.ImageField(default='homepage.jpg', upload_to='homepage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image2',
            field=models.ImageField(default='homepage.jpg', upload_to='homepage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image3',
            field=models.ImageField(default='homepage.jpg', upload_to='homepage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text1',
            field=models.CharField(default='text1', max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text2',
            field=models.CharField(default='text2', max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text3',
            field=models.CharField(default='text3', max_length=500),
        ),
        migrations.AddField(
            model_name='menu',
            name='heading',
            field=models.CharField(default='heading', max_length=50),
        ),
        migrations.AddField(
            model_name='menu',
            name='image1',
            field=models.ImageField(default='menu.jpg', upload_to='menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='image2',
            field=models.ImageField(default='menu.jpg', upload_to='menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='image3',
            field=models.ImageField(default='menu.jpg', upload_to='menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='text1',
            field=models.CharField(default='text1', max_length=500),
        ),
        migrations.AddField(
            model_name='menu',
            name='text2',
            field=models.CharField(default='text2', max_length=500),
        ),
        migrations.AddField(
            model_name='menu',
            name='text3',
            field=models.CharField(default='text3', max_length=500),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='description',
            field=models.TextField(default='description', max_length=3000),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='heading',
            field=models.CharField(default='hading', max_length=500),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='btn',
            field=models.CharField(default='button', max_length=20),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='heading',
            field=models.CharField(default='heading', max_length=500),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(default='name', max_length=50),
        ),
    ]
