# Generated by Django 4.2.7 on 2023-11-29 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_rename_datetime_customer_date_customer_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, max_length=50),
        ),
    ]
