# Generated by Django 3.2.23 on 2023-11-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0024_chefs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ourmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=50)),
                ('foodimage', models.ImageField(upload_to='ourmenu')),
                ('description', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
