# Generated by Django 3.2.23 on 2023-11-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0026_ourmenu_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourmenu',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='Dinner', max_length=50),
        ),
    ]
