# Generated by Django 4.2.7 on 2023-11-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0027_alter_ourmenu_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='btn2',
            field=models.CharField(default='button', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='description2',
            field=models.TextField(default='description', max_length=3000),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heading2',
            field=models.CharField(default='heading', max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text4',
            field=models.CharField(default='text1', max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text5',
            field=models.CharField(default='text2', max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text6',
            field=models.CharField(default='text3', max_length=500),
        ),
    ]
