# Generated by Django 4.2.7 on 2023-11-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0030_delete_menu_homepage_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='img1',
            field=models.ImageField(default='homepage.jpg', upload_to='homepage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='img2',
            field=models.ImageField(default='homepage.jpg', upload_to='homepage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='img3',
            field=models.ImageField(default='homepage.jpg', upload_to='homepage'),
        ),
    ]
