# Generated by Django 4.2.7 on 2023-11-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0031_homepage_img1_homepage_img2_homepage_img3'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='img1',
            field=models.ImageField(default='homepage.jpg', upload_to='homepage'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='img2',
            field=models.ImageField(default='homepage.jpg', upload_to='homepage'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='img3',
            field=models.ImageField(default='homepage.jpg', upload_to='homepage'),
        ),
    ]
