# Generated by Django 4.2.7 on 2023-11-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0032_aboutpage_img1_aboutpage_img2_aboutpage_img3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='img1',
            field=models.ImageField(default='homepage.jpg', upload_to='aboutpage'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='img2',
            field=models.ImageField(default='homepage.jpg', upload_to='aboutpage'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='img3',
            field=models.ImageField(default='homepage.jpg', upload_to='aboutpage'),
        ),
    ]
