# Generated by Django 4.2.7 on 2023-11-30 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0034_ourmenu_btn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourmenu',
            name='btn',
        ),
    ]
