# Generated by Django 4.2.7 on 2023-11-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0036_happy'),
    ]

    operations = [
        migrations.AddField(
            model_name='happy',
            name='image',
            field=models.ImageField(default='happy.jpg', upload_to='ourmenu'),
        ),
        migrations.AlterField(
            model_name='happy',
            name='text1',
            field=models.CharField(default='text1', max_length=500),
        ),
        migrations.AlterField(
            model_name='happy',
            name='text2',
            field=models.CharField(default='text2', max_length=500),
        ),
        migrations.AlterField(
            model_name='happy',
            name='text3',
            field=models.CharField(default='text3', max_length=500),
        ),
        migrations.AlterField(
            model_name='happy',
            name='text4',
            field=models.CharField(default='text4', max_length=500),
        ),
    ]
