# Generated by Django 4.2.7 on 2023-11-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0038_testimony'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimony',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='testimony',
            name='image2',
            field=models.ImageField(default='testimony.jpg', upload_to='testimony'),
        ),
        migrations.AddField(
            model_name='testimony',
            name='image3',
            field=models.ImageField(default='testimony.jpg', upload_to='testimony'),
        ),
        migrations.AddField(
            model_name='testimony',
            name='image4',
            field=models.ImageField(default='testimony.jpg', upload_to='testimony'),
        ),
        migrations.AddField(
            model_name='testimony',
            name='name1',
            field=models.CharField(default='text2', max_length=500),
        ),
        migrations.AddField(
            model_name='testimony',
            name='name2',
            field=models.CharField(default='text2', max_length=500),
        ),
        migrations.AddField(
            model_name='testimony',
            name='name3',
            field=models.CharField(default='text2', max_length=500),
        ),
        migrations.AddField(
            model_name='testimony',
            name='name4',
            field=models.CharField(default='text2', max_length=500),
        ),
        migrations.AddField(
            model_name='testimony',
            name='position1',
            field=models.TextField(default='text3', max_length=500),
        ),
        migrations.AddField(
            model_name='testimony',
            name='position2',
            field=models.TextField(default='text3', max_length=500),
        ),
        migrations.AddField(
            model_name='testimony',
            name='position3',
            field=models.TextField(default='text3', max_length=500),
        ),
        migrations.AddField(
            model_name='testimony',
            name='position4',
            field=models.TextField(default='text3', max_length=500),
        ),
        migrations.AddField(
            model_name='testimony',
            name='text4',
            field=models.CharField(default='text1', max_length=500),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='text1',
            field=models.CharField(default='text1', max_length=500),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='text2',
            field=models.CharField(default='text1', max_length=500),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='text3',
            field=models.CharField(default='text1', max_length=500),
        ),
    ]
