# Generated by Django 4.2.7 on 2023-11-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0039_rename_image_testimony_image1_testimony_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='image5',
            field=models.ImageField(default='testimony.jpg', upload_to='testimony'),
        ),
        migrations.AddField(
            model_name='testimony',
            name='name5',
            field=models.CharField(default='text2', max_length=500),
        ),
        migrations.AddField(
            model_name='testimony',
            name='position5',
            field=models.TextField(default='text3', max_length=500),
        ),
        migrations.AddField(
            model_name='testimony',
            name='text5',
            field=models.CharField(default='text1', max_length=500),
        ),
    ]
