# Generated by Django 4.2.7 on 2023-11-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0041_alter_testimony_position1_alter_testimony_position2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='text1', max_length=500)),
                ('heading', models.CharField(default='text2', max_length=500)),
                ('text', models.TextField(default='text3', max_length=500)),
                ('btn', models.CharField(default='button', max_length=20)),
            ],
        ),
    ]
