# Generated by Django 4.2.7 on 2023-11-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0043_alter_aboutend_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='background',
            field=models.ImageField(default='testimony.jpg', upload_to='testimony'),
        ),
    ]
