# Generated by Django 4.2.7 on 2025-03-28 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0056_alter_order_customer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_name',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_phone',
            new_name='client_phone',
        ),
    ]
