# Generated by Django 4.2.7 on 2023-11-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_alter_customer_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='date',
            new_name='datetime',
        ),
    ]
