# Generated by Django 4.2.7 on 2023-11-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_remove_aboutpage_image1_remove_aboutpage_image2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Desserts',
        ),
        migrations.DeleteModel(
            name='Dinner',
        ),
        migrations.DeleteModel(
            name='Drinks',
        ),
        migrations.DeleteModel(
            name='Lunch',
        ),
        migrations.DeleteModel(
            name='Winecard',
        ),
        migrations.AddField(
            model_name='menu',
            name='text10',
            field=models.CharField(default='text4', max_length=500),
        ),
        migrations.AddField(
            model_name='menu',
            name='text11',
            field=models.CharField(default='text5', max_length=500),
        ),
        migrations.AddField(
            model_name='menu',
            name='text12',
            field=models.CharField(default='text6', max_length=500),
        ),
        migrations.AddField(
            model_name='menu',
            name='text16',
            field=models.CharField(default='text4', max_length=500),
        ),
        migrations.AddField(
            model_name='menu',
            name='text17',
            field=models.CharField(default='text5', max_length=500),
        ),
        migrations.AddField(
            model_name='menu',
            name='text18',
            field=models.CharField(default='text6', max_length=500),
        ),
        migrations.AddField(
            model_name='menu',
            name='text19',
            field=models.CharField(default='text4', max_length=500),
        ),
        migrations.AddField(
            model_name='menu',
            name='text20',
            field=models.CharField(default='text5', max_length=500),
        ),
        migrations.AddField(
            model_name='menu',
            name='text21',
            field=models.CharField(default='text6', max_length=500),
        ),
        migrations.AddField(
            model_name='menu',
            name='text4',
            field=models.CharField(default='text4', max_length=500),
        ),
        migrations.AddField(
            model_name='menu',
            name='text5',
            field=models.CharField(default='text5', max_length=500),
        ),
        migrations.AddField(
            model_name='menu',
            name='text6',
            field=models.CharField(default='text6', max_length=500),
        ),
        migrations.AddField(
            model_name='menu',
            name='text7',
            field=models.CharField(default='text4', max_length=500),
        ),
        migrations.AddField(
            model_name='menu',
            name='text8',
            field=models.CharField(default='text5', max_length=500),
        ),
        migrations.AddField(
            model_name='menu',
            name='text9',
            field=models.CharField(default='text6', max_length=500),
        ),
    ]
