# Generated by Django 4.2.7 on 2023-11-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0022_alter_customer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='text1',
            field=models.TextField(default='text1', max_length=500),
        ),
        migrations.AlterField(
            model_name='stories',
            name='text2',
            field=models.TextField(default='text2', max_length=500),
        ),
        migrations.AlterField(
            model_name='stories',
            name='text3',
            field=models.TextField(default='text3', max_length=500),
        ),
        migrations.AlterField(
            model_name='stories',
            name='text4',
            field=models.TextField(default='text4', max_length=500),
        ),
        migrations.AlterField(
            model_name='stories',
            name='text5',
            field=models.TextField(default='text5', max_length=500),
        ),
        migrations.AlterField(
            model_name='stories',
            name='text6',
            field=models.TextField(default='text6', max_length=500),
        ),
    ]
