# Generated by Django 3.2.23 on 2023-11-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0025_ourmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourmenu',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breko'), ('lunch', 'Lunch'), ('dinner', 'Supper'), ('snack', 'Kakitu')], default='Dinner', max_length=50),
        ),
    ]
