# Generated by Django 4.2.7 on 2023-11-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0029_alter_ourmenu_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.AddField(
            model_name='homepage',
            name='background_image',
            field=models.ImageField(default='homepage.jpg', upload_to='homepage'),
        ),
    ]
