# Generated by Django 4.2.7 on 2023-11-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0035_remove_ourmenu_btn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Happy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.TextField(default='text1', max_length=500)),
                ('text2', models.TextField(default='text2', max_length=500)),
                ('text3', models.TextField(default='text3', max_length=500)),
                ('text4', models.TextField(default='text4', max_length=500)),
            ],
        ),
    ]
