# Generated by Django 4.2.7 on 2023-11-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0040_testimony_image5_testimony_name5_testimony_position5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='position1',
            field=models.CharField(default='text3', max_length=500),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='position2',
            field=models.CharField(default='text3', max_length=500),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='position3',
            field=models.CharField(default='text3', max_length=500),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='position4',
            field=models.CharField(default='text3', max_length=500),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='position5',
            field=models.CharField(default='text3', max_length=500),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='text1',
            field=models.TextField(default='text1', max_length=500),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='text2',
            field=models.TextField(default='text1', max_length=500),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='text3',
            field=models.TextField(default='text1', max_length=500),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='text4',
            field=models.TextField(default='text1', max_length=500),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='text5',
            field=models.TextField(default='text1', max_length=500),
        ),
    ]
