# Generated by Django 4.2.7 on 2023-11-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0042_aboutend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutend',
            name='text',
            field=models.TextField(default='text3', max_length=2000),
        ),
    ]
