# Generated by Django 4.2.7 on 2023-11-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0045_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stories',
            old_name='text2',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='stories',
            old_name='text1',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='stories',
            old_name='text3',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='text4',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='text5',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='text6',
        ),
        migrations.AddField(
            model_name='stories',
            name='image',
            field=models.ImageField(default='blog.jpg', upload_to='blog'),
        ),
    ]
