# Generated by Django 4.2.7 on 2023-11-30 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0047_alter_stories_date_alter_stories_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stories',
            old_name='text',
            new_name='text1',
        ),
    ]
