# Generated by Django 4.2.7 on 2025-03-24 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0050_table_alter_customer_date_alter_customer_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', message='Name can only contain letters and spaces.')]),
        ),
    ]
