# Generated by Django 4.2.7 on 2025-03-24 17:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0052_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourmenu',
            name='stock',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='ourmenu',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert'), ('winecard', 'Winecard'), ('drinks', 'Drinks')], default='dinner', max_length=50),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Phone number has to be 10 digits.')])),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.ourmenu')),
            ],
        ),
    ]
